### ISSUE TITLE
Datenschutzerklärung ergänzen

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#1]
- [x] Verantwortlicher (Michael)
- [x] IP-Adresse wird auch vom Github-Server geloggt?
- [x] Wie lange werden Daten gespeichert  (jeweils)
- [x] Datenschutzerklärung auf Website veröffentlichen (sobald es die gibt)
- [x]  Cookies (wer welche und warum und wie kann man es verhindern)

[...]

**Comment by ValorNaram** [comment]
https://help.github.com/articles/github-privacy-statement/#what-information-github-collects-and-why

**Comment by ValorNaram** [comment]
Theoretisch müssten wir, da wir selber keine Daten erheben, sondern die Drittanbieter, nur auf die Datenschutzerklärung dieser verweisen und wofür diese jeweils zuständig sind.

**Comment by ValorNaram** [comment]
Ich strebe allerdings eine allgemeine Aufklärung über das Thema an.

**Comment by ValorNaram** [comment]
Bist Du mit der README.md zufrieden?

**Comment by Discostu36** [comment]
Grundsätzlich schon, mit folgenden Einschränkungen:
- Die Datenschutzerklärung sollte in einer eigenen HTML-Seite stehen
- Ich würde für diese Fassung ein paar Abschnitte kürzen
- Gleichzeitig würde ich ein paar Abschnitte hinzufügen, die offenbar rechtlich vorgeschrieben sind
- Das wird u.U. dazu führen, dass sie uneinheitlich in ihrem Stil wird.
- Am Ende muss dieser Text auch übersetzt werden.

**Comment by ValorNaram** [comment]
Die Datenschutzerklärung sollte in einer eigenen HTML-Seite stehen

Ist möglich.

    Ich würde für diese Fassung ein paar Abschnitte kürzen

Welche?

    Gleichzeitig würde ich ein paar Abschnitte hinzufügen, die offenbar rechtlich vorgeschrieben sind

Ich habe in der DSGVO nichts weiteres dazu gefunden. Ein Opt-Out kann es aus technischen Gründen nicht geben. Wir sammeln selber keine Daten oder geben dieses in Auftrag. Die Seiten Dritter, die zum schnellen Laden der Babykarte mittels Caching notwendig sind, entscheiden selber, ob sie Daten sammeln oder nicht. Ich kann natürlich die Dateien, die die Babykarte benötigt, herunterladen und in dieses Repositorie einbinden. Dadurch würde aber das Caching verloren gehen. Es wäre aber durchaus zu überlegen, eine Version der Babykarte bereitzustellen, die möglichst wenig Dateien Seiten Dritter herunterläd und somit auf Caching komplett oder ansatzweise verzichtet (Seite läd unter anderem dann etwas langsamer und verbraucht auch mehr Speicher).

    Das wird u.U. dazu führen, dass sie uneinheitlich in ihrem Stil wird.

Das ist mir egal. Sog. Datenschützer haben für die DSGVO gesorgt. Ich persönlich hätte mir gewünscht, wenn der Wunsch nach solchem Gesetzt aus der Mitte der Gesellschaft gekommen wäre und nicht durch Lobbyisten.

    Am Ende muss dieser Text auch übersetzt werden.

Selbstverständlich!


**Beachte: Dieses Projekt ist FOSS und keine Dienstleistung**

**Comment by ValorNaram** [comment]
Es sei denn Du willst es als Dienstleistung aufziehen. Also von wegen wir machen das um Nutzer vorrangig glücklich zu machen. Für mich persönlich ist es keine Dienstleistung, da ich mit der Kaffeekarte und Babykarte nur lediglich das potenzielle Potenzial von OpenStreetMap aufzeigen möchte. Die Kaffeekarte steht übrigens auf der Kippe und ich muss bald eine nicht so leichte Entscheidung treffen.

**Comment by Discostu36** [comment]
In ihrem jetzigen Status ist die Baby-Karte FOSS. Wir stellen nur den Quelltext bereit, mit dem man die Website veröffentlichen kann. Wenn wir die Website aber selbst veröffentlichen, dann sind wir eben auch an die Gesetzte gebunden, die damit verbunden sind. Ob wir wollen, dass es eine Dienstleistung ist oder nicht, ist dabei nicht besonders relevant. Davon abgesehen, dass ich persönlich schon schön finden würde, wenn es kein reines Vorführ-Projekt bleibt ("Sowas geht mit OSM"), sondern es Leute tatsächlich auch nutzen würden.

Wir sammeln keine Daten, aber wir verarbeiten Daten. Wir leiten nämlich die persönlichen Daten der Websitebesucher an Dritte weiter. Das reicht schon, um unter die DSGVO zu fallen.

Ich weiß, dass ich damit übervorsichtig bin. Solange wir nicht gewerblich werden, wird sich da wohl kaum ein Abmahnanwalt bemühen. Aber ich bin lieber übervorsichtig, als irgendwann Probleme zu bekommen...

**Comment by ValorNaram** [comment]
Das wir unter die DSGVO fallen, ist selbstverständlich. Genau aus diesem Grund habe ich die Datenschutzerklärung auch geschrieben, ansonsten gäbe es die nur nach Anfrage.

Für mich ist es ein "Vorführprojekt", für Dich soll es wirklich ein Nutzen haben. Missionen sind unterschiedlich und ich bin froh Dir bei Deiner individuellen Mission von Behelf zu sein.

**Comment by Discostu36** [comment]
Ist jetzt fertig, jetzt fehlt nur noch

- [ ] Konvertieren
- [ ] Übersetzen

**Comment by Discostu36** [comment]
Important: Links to Privacy Policy and Impressum must always be visible, also in mobile view (legal requierement).

**Comment by ValorNaram** [comment]
This would break the flow. What the hell? They can't press a menubutton? Also a lawmaker should be able to press a button.

**Comment by Discostu36** [comment]
GDPR is not about lawmakers but about "ordinary people". The idea is, that they shouldn't have to look for the privacy policy but that it should be reachable with a single click.  

I think we should do it like already once commited by me and reverted by you: In a small font next to the language symbols.

**Comment by Discostu36** [comment]
Text is now final, please convert.

**Comment by Discostu36** [comment]
I've moved the links to privacy policy and Impressum. Feel free to make the code cleaner (without inline css).
