### ISSUE TITLE
Adding a filter for POIs tagged with `playground=`

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#100]
### A problem encountered while trying to solve #93 
While working on #93 I encountered the problem of not really understanding the Overpass QL (Overpass query language). That's why I am creating this new issue here so I can work on something Babykarte related

### What this issue is for
This issue describes a new feature for Babykarte to load POIs with tag scheme `playground=` and then apply a different popup scheme to it, see #99

**They are some option how to do it:**
- Creating a new filter just fetching seperated tagged playground equipment without connecting it to the playground itself.
  - A click on the `playground` filter activates this new filter too
  - A click on the `playground` filter does nothing to this filter. Meaning this new filter is independ from the `playground` filter
- Adding of the query needed for fetching seperated tagged playground to the filter `playground`
  - Since I am planning to connect filters with the popup information and formatting rules describing database (JSON variable), this can introduce some problems of how to take playground POIs and playground equipment apart but this can be easily solved.

**Comment by ValorNaram** [comment]
#99 closed. Now I will work on this issue. Please leave a reply to the _They are some option how to do it:_ section of my start post so I know how to do it/what to do.

**Comment by NicolasGrosjean** [comment]
If you put a new filter, I think it is better to put it dependent to the existing one.

For example we can have only these cases :
![image](https://user-images.githubusercontent.com/13560473/60542897-4b9d8800-9d15-11e9-8d54-73ddeafc01b8.png)

_I have not thought about the color of the new filter_

I have not understood the last option.

**Comment by Discostu36** [comment]
I also don't understand the last option :-)

But I do like Nicolas' suggestion. I'd call the filter "Playground equipment", though.

**Comment by ValorNaram** [comment]
> I have not understood the last option.

It's about combining the two filters into one. A click on the `playground` filter not just loads and shows playgrounds but also their equipment.

**Comment by Discostu36** [comment]
I think Nicolas' idea is actually better. But I'm not sure if this should also influence the "playgrounds as area" rendering or not (only area when equipment is selected?).

**Comment by ValorNaram** [comment]
This is related to https://github.com/babykarte/babykarte.github.io/issues/84#issuecomment-507821799 and now I have to do the following:

- [ ] Introducing filter event triggers.
- [ ] Creating new filter and assign a colour to it.
- [ ] Filter depended popups, creating new popup scheme for the newly created filter.
- [ ] Assign popup to filters.
