### ISSUE TITLE
Playground features issues

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#101]
The new feature from #88 has still some issues:
- Playground features are shown in the tab when there are none
- Undefined baby friendliness features are shown (please only at cafes and restaurants)

(in other words: this tab should be empty)

![grafik](https://user-images.githubusercontent.com/30999326/60622818-7ce38a00-9de1-11e9-83f0-4f3a66b9d51e.png)

**Comment by Discostu36** [comment]
This issue is still there 
![grafik](https://user-images.githubusercontent.com/30999326/62462972-13142280-b789-11e9-9087-4d23bbe7efd2.png)

**Comment by ValorNaram** [comment]
Please reopen the issue next time :)

**Fixed**
