### ISSUE TITLE
Popup for playground equipment

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#103]
# This references to #93, #100, #84, #99 and https://github.com/babykarte/babykarte.github.io/issues/84#issuecomment-507821799

## What is this about
In this issue we will talk about the content of the popup for playground equipment. So we can show users the most important information they likely want and love.

## What to do to get this solved
- [x] Agreeing on the content level
- [x] The function `js/overpass.js/babyTab` needs to be more abstract (supporting multiple databases for popup content displaying and clustering rules). Currently we have just one database as a JSON variable `js/overpass.js/babyData`. In future they will be two or more that must be handled by the function. Function `js/overpass.js/babyTab` must be renamed in `js/overpass.js/processContentDatabase` or similar.
- [x] ~The popup content displaying and clustering rules coloring rule defined in a JSON variable `js/overpass.js/colorcode` must be manually feed to the `js/overpass.js/processContentDatabase` function so it can be excluded for the run for playground equipment popup rendering ergo **no coloring for the "bullet points" (see https://github.com/babykarte/babykarte.github.io/issues/84#issuecomment-507821799 for the meaning of this wording)~
- [x] ~???~ Provide fallback for cases in which playground equipment POIs aren't equiped with the [name](https://wiki.openstreetmap.org/wiki/Key:name) key ~. ??? **Don't know how to develop this**~ with conditional sentences (code)
- [x] ~??? Provide a subtitle which unveils the type of the playground equipment to the user. Perhaps checking of match in "leisure" --> "children" in JSON variable `js/overpass.js/babyData` ??? **Cannot think about a better option yet**~ Get subtitles with function `js/filters.js/getSubtitle`

**Comment by ValorNaram** [comment]
# Agreeing on the content level

See https://github.com/babykarte/babykarte.github.io/issues/84#issuecomment-507821799 to get an idea what I am talking about. you may discuss which tags Babykarte must evaluate and show.

**Comment by Discostu36** [comment]
baby
wheelchair
surface
description
access
min_age
max_age
material
Capacity

**Comment by ValorNaram** [comment]
> baby

No specification found in wiki.

> surface

Which values are logical to apply on a playground equipment?

> access

Which values are logical to apply on a playground equipment?

**Comment by ValorNaram** [comment]
@Discostu36 See my as unstable labeled commit. It is really that what you want? Most of the information the keys from your list unveil are not important for Mainstream society.

**Comment by ValorNaram** [comment]
Someone should preview the translation in english and german.

@NicolasGrosjean Please don't translate in french yet, first it must be previewed, corrected and improved. But I added the entries you need to translate right into `js/fr.js` so you can start translating easily when the time and air is right.

@Discostu36 I played with the german language a little bit and added some humour. Some example: `gehackter geschnitzelter Holzboden`

@team Please preview, correct and reupload.

**Comment by Discostu36** [comment]
I'll work on it when I'm back from vacation.

**Comment by Discostu36** [comment]
> > baby
> 
> No specification found in wiki.

https://wiki.openstreetmap.org/wiki/Key:playground#Descriptive_tags

**Comment by Discostu36** [comment]
Please replace the list of materials with this one:

- wood
- plastic
- rope
- steel
- metal

This covers 95% of material tags on playground equipment (at least in Europe).

**Comment by Discostu36** [comment]
I actually don't know what is interesting for consumers and what is not. But if the data is there we should show it.

**Comment by Discostu36** [comment]
I'll have a look at the surface list later this week. Sorry for the delay.

**Comment by Discostu36** [comment]
Please use these surfaces (91 %):
([Source](https://overpass-turbo.eu/s/KVN))

- sand
- grass
- woodchips
- rubbercrumb
- tartan
- gravel
- paving_stones
- wood
- asphalt

**Comment by ValorNaram** [comment]
@Discostu36 Please check my [commit](https://github.com/babykarte/babykarte.github.io/commit/e64443a257803add0ac5a0b5a1c4a945948998ec) and make changes to the german translation and english translation (if any).

@NicolasGrosjean Please don't translate to french yet. If you want you can help improving the translation for english in file `js/en.js`

**Comment by NicolasGrosjean** [comment]
I have an issue when there is a lot of text in the popup

![image](https://user-images.githubusercontent.com/13560473/62414777-85b5be80-b620-11e9-9109-2b991ded769b.png)

[Url to reproduce it](http://localhost:8080/#19&45.18743416657465&5.713295325549553)

**Comment by NicolasGrosjean** [comment]
I have not succeeded to display [a specific playground in Babykarte](http://localhost:8080/#19&44.8008206&5.7068677).

**Comment by ValorNaram** [comment]
> I have some alignment issues when there is a lot of text in the popup

Are you sure this alignment issue only occurrs when there's a lot of text in the popup?

**Comment by Discostu36** [comment]
@NicolasGrosjean The playground is not displayed because its min_age doesn't make it suitable for Babykarte.

**Comment by NicolasGrosjean** [comment]
@ValorNaram You are right, it is not linked to the size of the popup, there was alignment issues in all other popup

![image](https://user-images.githubusercontent.com/13560473/62421607-ff8f8b80-b6a4-11e9-8737-4a41edff337b.png)

![image](https://user-images.githubusercontent.com/13560473/62421611-0ae2b700-b6a5-11e9-85bf-4b8158562821.png)

**Comment by NicolasGrosjean** [comment]
@Discostu36 Thanks for the answer.

A month ago, you have listed a list of attributes to display. The list has been shorten ?

> baby
> wheelchair
> surface
> description
> access
> min_age
> max_age
> material
> Capacity

For example, I don't see min_age and max_age in [these 2 playgrounds equipment](http://localhost:8080/#19&44.3370685&2.5738223).

For the climbing one, it is also strange to have Playground equipment as name.
![image](https://user-images.githubusercontent.com/13560473/62421761-29e24880-b6a7-11e9-8281-99772470f5a3.png)

**Comment by ValorNaram** [comment]
> A month ago, you have listed a list of attributes to display. The list has been shorten ?

Might be that I forget them to add because initialy I had to leave them out. I will investigate that.

**Comment by ValorNaram** [comment]
> For the climbing one, it is also strange to have Playground equipment as name.

The combination `playground=climbing` isn't supported because it is
- not being standardized nor documented or
- not very often used

that's why there is no string defined in the language reference files. The name `Playground equipment` is a fallback Babykarte shows in cases like these.

**Comment by ValorNaram** [comment]
> @ValorNaram You are right, it is not linked to the size of the popup, there was alignment issues in all other popup. The issue is not the same as yesterday.

Please tell me which browser and which operating system do you use. I cannot reproduce your problem but depending on your answer it may be necessary to tweak the CSS rules how a browser should/must render. I hope it is no issue with the emojis/icons itself.

**Comment by ValorNaram** [comment]
> The list has been shorten?

No we did not short the list. But sometimes we discuss things related to Babykarte privately via Telegram. We know that's not very transparent but sometimes things are better to solve throw chatting or voice telephony. But we keep this to a minimum. Much of the Babykarte stuff will be posted here. @NicolasGrosjean You're member of the Babykarte team, so if you have interest and have Telegram, just drop @Discostu36 or me an email with your Telegram username and we open up a group of three.

Despite this we have currently no plans to open our conversation to the public which would be very easy with Telegram.

**Comment by NicolasGrosjean** [comment]
Firefox Quantum 68.0.1 (64 bits) on Windows 10

**Comment by Discostu36** [comment]
Please remove min_age and max_age from the pop-up when not defined.

**Comment by Discostu36** [comment]
Two things I'd like to know if they're still on your to-do list:
- Dots instead of markers for playground equipment
- Resizing of popups according to content

**Comment by ValorNaram** [comment]
> - Dots instead of markers for playground equipment
> - Resizing of popups according to content

**Done**

**Comment by ValorNaram** [comment]
@Discostu36 Are you finish improving the translation of english and german?

**Comment by Discostu36** [comment]
Yes, I think I am. 

**Still one bug:**
The additional information are not displayed (tested with [this swing](http://localhost:8080/#19&54.32821503499246&10.122293561653352) [baby=] and [this structure](http://localhost:8080/#19&54.41297719890651&10.413262277797914) [surface=])

**Comment by ValorNaram** [comment]
> Still one bug:

**Bug has been fixed by me!**

**Comment by ValorNaram** [comment]
## Translating into french

@NicolasGrosjean you are now allowed to translate some strings into french :) Everything has been prepared just for your show (I am just a little bit joking :)).

I incoporated @Discostu36 s' changes he's made in the english translation into the french translation file. Be sure to fetch the newest version of the code from the `beta` branch. Just edit the `js/fr.js` file in `devel`. With the `find` function you can search the document for the string pieces ending with `(EN)`. This should make it pretty easy for you to translate.

**Comment by ValorNaram** [comment]
> @ValorNaram You are right, it is not linked to the size of the popup, there was alignment issues in all other popup. The issue is not the same as yesterday.

Does this problem persists? I tweaked the design a little bit in order to be more friendly to mobile users.

**Comment by Discostu36** [comment]
Playground equipment is still in the pop-up when there is none tagged:

![grafik](https://user-images.githubusercontent.com/30999326/62805338-f9a80900-baef-11e9-9e51-781d901200b2.png)

**Comment by ValorNaram** [comment]
Is it really a bug? It says "Playground equipment" on playgrounds and in real life there are playground equipments on every playground (proove me wrong).

**Comment by Discostu36** [comment]
Sure there are, but it's useless information. We could also add "food available" to every restaurant...

**Comment by ValorNaram** [comment]
**Ok! Babykarte now behaves differently**
