### ISSUE TITLE
changing_table=limited not shown

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#106]
https://babykarte.github.io/#19&54.32228820781011&10.126189291477205
Fresco

Live version (not tested in local).
Changing table tagged as limited, not shown in baby friendliness tab.

**Comment by ValorNaram** [comment]
Unfortunately, I removed or did not add the language reference for `limited`

- `PDV_CHANGINGTABLE_LIMITED`
- `PDV_DIAPER_LIMITED`

**They have been added now.**
