### ISSUE TITLE
New tiles

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#108]
I am always thinking about reducing the burden we put on the OSM servers which are donated servers. I've now found a new tiles server. [Check it out](https://maps.wikimedia.org/#4/40.75/-73.96). It's [Wikimedia maps](https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use)

But before we jump to a new tile servers we need to do the following.

- [ ] Reading & understanding the [Wikimedias' Maps Terms of Use]/https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use) and [Wikimedias' Terms of Use](https://foundation.wikimedia.org/wiki/Terms_of_Use/en)
- [ ] In our own Privacy Policy we need to link to the [Privacy Policy from Wikimedia](https://foundation.wikimedia.org/wiki/Privacy_policy) in the respective language french, english or german.
- [ ] Modifying the Privacy Policy in all languages Babykarte supports.

**Comment by ValorNaram** [comment]
So if we want to change then we need to do that.

**Comment by Discostu36** [comment]
I don't really see a difference between putting a burden on OSM and Wikimedia. And I don't think that the few users we're having are making a big difference. And, maybe most important, I don't think the Wikimedia rendering is good for our purposes, for example playground areas are not rendered.
