### ISSUE TITLE
Missing German translation for healthcare:speciality

### ISSUE THREAD

**Issue by sdicke** [babykarte/babykarte.github.io#116]
It would be nice if the German translation would cover the healthcare:speciality tag.

Examples:
https://www.openstreetmap.org/node/6359478597
https://www.openstreetmap.org/node/4195375166
https://www.openstreetmap.org/node/4810117234
![Screenshot_20190813_153124](https://user-images.githubusercontent.com/23293203/62946423-f14a1980-bde0-11e9-8271-2f708bf645d5.png)

**Comment by sdicke** [comment]
Okay. The translation are there and are used. But there is another problem: If a popup once showed and the display language is changed, the strings in the popups are unchanged. When the default language is English and you open a popup, the strings are in English. When you then change the language to German, the previously shown popups leave in English, but the previously not shown popups are in German.

**Comment by Discostu36** [comment]
This is a known problem, but @ValorNaram has decided not to fix it because it's unusual behaviour for a normal user to switch language after selecting a filter...

**Comment by ValorNaram** [comment]
I "fixed" it in the `devel` branch.

**Comment by ValorNaram** [comment]
but I see some errors

**Comment by ValorNaram** [comment]
**Fixed**
