### ISSUE TITLE
Redundant subtitles for playground equipment

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#119]
This seems to have happened with one of the last commits. Subtitles are always displayed instead of only when the equipment is named.

![grafik](https://user-images.githubusercontent.com/30999326/63120419-8e07e500-bfa2-11e9-9dc6-703f1d0ae6be.png)

This should be fixed before we officially release v2.5.

**Comment by ValorNaram** [comment]
Are you sure that you have the up to date branch. During my own tests I did not have this problem or even better I took care that we don't have this problem.

**Comment by ValorNaram** [comment]
Removed a code after validation by accident without taking notice. Sometimes the feature that the windows focus follows my mouse can lead to such fails. By the way: It allows me to work faster.

I apologize for that.

**Comment by Discostu36** [comment]
Doesn't seem to be fixed.

**Comment by ValorNaram** [comment]
Now it's really fixed!

**This bug occurred just because I deleted an important code part and I did not see it.**
