### ISSUE TITLE
Opening hours

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#15]
Due to some problems in the implementation of opening hours in Babykarte, it remains without it.

Meaning v.1 will be developed and published without this implementation when no solution can be found during this period.

**Comment by carstenhag** [comment]
Seems to be implemented on the live version already?

**Comment by ValorNaram** [comment]
> Seems to be implemented on the live version already?

Yes and no. I implemented my own algorithm rather than using the "opening_hours" js library which is being developed for that purpose.

**Comment by ValorNaram** [comment]
@carstenhag It's not the right way of how i opened and described the feature here. Will close this but will open another issue.
