### ISSUE TITLE
Ready for deploying

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#20]
All steps are done, now we come to the final - the publication of Babykarte by activating its domain http://babykarte.github.io/ as we discussed in #19 .

# Lists
List of special sites:
- [ ] Impressum ( `impress.html` )
- [ ] Impress (`impress.html` )
- [ ] Datenschutzerklärung ( `privacypolicy-de.html` )
- [ ] Privacy Policy ( `privacypolicy-en.html` )

The main page:
- [ ] Babykarte ( `index.html` )

Others:
- [ ] Following Branding rules for the Facebook logo (See [this example](http://localhost:8080/#19&54.347328667801214&10.141067236727396) of the use in Babykarte and check the compliance with Facebook's rules)

Perhaps you want to check all of these before activating the domain or you leave the check out. It's your choice.

# How to activate the domain?
1. Go to **settings** of this repository.
2. Scroll down to _Github Pages_
3. Select from the `None` dropdown list the `master branch` (it's the branch we're currently in and what we use for working releases. Reminder: We've talked about branches and how I am going to handle further commits into this repository. For v2.0 I create another branch where I upload the commits to v.2.0)
4. You may also want to rename this repository `Baby-Karte` to `babykarte` in order to have http://babykarte.github.io/ instead of http://baby-karte.github.io/

**Comment by Discostu36** [comment]
v1.0 doesn't have to be perfect, but the tab about baby friendliness still needs some work. Take [this restaurant](http://localhost:8080/#19&54.347328667801214&10.141067236727396) as an example:

- [ ] Formatting has to be corrected (no bold for diaper, every information in own line, maybe use ``<ul>``). 
- [ ] highchair is missing
- [ ]  Information from the sub keys (diaper:female, diaper:male) is missing.

I also haven't done my small additions to the privacy policy yet.

**Comment by ValorNaram** [comment]
Repo updated and https://github.com/Discostu36/Baby-Karte/issues/20#issuecomment-471742220 fulfilled

**Comment by Discostu36** [comment]
I've tried to publish but couldn't manage to get the url babykarte.github.io. Do I have to create a separate user account for that?

**Comment by ValorNaram** [comment]
1. Go to https://github.com/Discostu36/babykarte/settings
2. Scroll down to _Github Pages_
3. In the _Source_ section click on the dropdown.
4. Select _master branch_
5. The site reloads and all is set up and running

**Comment by Discostu36** [comment]
Yes, you already told me that. But I can only publish at https://Discostu36.github.io/babykarte

**Comment by ValorNaram** [comment]
Yes, sry. You need to create an organisation.

1. Visit https://help.github.com/en/articles/creating-a-new-organization-from-scratch and follow the steps. The name of the organisation is `babykarte`
2. Create a new repository with the name `babykarte.github.io` See https://pages.github.com/ for more information
3. Add me as a member of that organisation
4. I will then reinitialize the repo by uploading all the files or you do it on your own

**Comment by ValorNaram** [comment]
**Organization created by @Discostu36**

**Comment by Discostu36** [comment]
I think the tiny issues we're still having shouldn't keep us from releasing v1 and going public tomorrow. Do you agree?

**Comment by ValorNaram** [comment]
I agree going public.

It's time to see how Babykarte fits into this world. Let's see and fire it
