### ISSUE TITLE
Diaper filter

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#22]
The diaper filter isn't correctly implemented yet:

- We don't need a separate toilet filter
- Diaper filter should be something like ``"(amenity=toilet|shop=chemist)" AND "diaper=*" WITHOUT "diaper=no"``

**Comment by ValorNaram** [comment]
Why not checking for `diaper=*` without `diaper=no` and without `amenity=toilet` or `shop=chemist`?

**Comment by Discostu36** [comment]
Because I want to get diaper changing tables that are available to the public, not every restaurant that has one.

**Comment by ValorNaram** [comment]
Mhhh Okay! See `diaper:access=public` on https://wiki.openstreetmap.org/wiki/Key:diaper#Additional_tags

My suggestion: `diaper!=no` and `diaper:access=public`

**Comment by Discostu36** [comment]
Not used widely enough. Is there anything wrong with my suggestion?

**Comment by ValorNaram** [comment]
It reduces the possibility for displaying diapers on toilets and on chemist only.

**Comment by Discostu36** [comment]
Well, we could use it as another possibility.

Display if:
- diaper=*
- Diaper!=no

And one of the following:
- amenity=toilets
- shop=chemist
- diaper:access=public

**Comment by ValorNaram** [comment]
`amenity=toilets` and `shop=chemist` don't need to be included since `diaper=*` and `diaper!=no` implicies them.

But `diaper:access=public` is a powerful key for your purpose. This **should** be included in all requests of this type.

**Comment by ValorNaram** [comment]
Do you agree my request from my previous comment?

**Comment by Discostu36** [comment]
Not really, no. I'd like to hit two birds with one stone
1. Have as many diaper changing tables on the map as possible
2. Make sure that almost all of them are available to the public.

I think that my suggestion is best for that, because separately mapped toilets and diaper changing tables in drug stores are almost always available to the public and diaper:access=public could provide some additional ones that belong to different POIs. Your suggestions either provide too many tables not available to the public (only using diaper and thus also showing restaurants etc.) or too few because the key is too rarely used (only using diaper:access=public).

At least this is my gut feeiling, I haven't compared results of the different overpass queries yet.

**Comment by ValorNaram** [comment]
Ok, let's see how your suggestion works at http://overpass-turbo.eu/s/H4K

Are you happy with the results?

**Comment by Discostu36** [comment]
I've tested with the city of Hamburg. Like with most of these tags there is not enough data yet (only 24 POIs). But yes, this is the kind of results that I wanted. The other queries provide no data at all or additional POIs that are useless for the situations I'm thinking about, because the diaper changing table is only available to paying customers (like "Miniatur Wunderland").

**Comment by ValorNaram** [comment]
Ok, already prepared the update. I just need to upload it.

**Comment by ValorNaram** [comment]
**Issue solved, now closing**

**Comment by Discostu36** [comment]
OK, I was wrong. My wife has just convinced me that diaper changing tables should always be shown, also when being in a cafe, restaurant or IKEA. She wouldn't hesitate to ask if she can use it without being a customer.

**Comment by ValorNaram** [comment]
You don't need to specify `diaper=*` and `diaper!=no`. A `diaper!=no` is enough

**Comment by ValorNaram** [comment]
But you need to additionally add `diaper`

**Comment by ValorNaram** [comment]
**Changed, now closing**

**Comment by bkil** [comment]
There is an ongoing proposal to enhance tagging of baby changing tables. Please share with whoever may be concerned and feel free to comment:
https://wiki.openstreetmap.org/wiki/Proposed_features/baby_changing_tables

**Comment by ValorNaram** [comment]
I am the initiator of the proposal.

It's me Valor Naram.

And yes, we will take it into account but thank you for remembering us.

**Comment by bkil** [comment]
@ValorNaram Yes, I've seen your name :) Still, I felt that linking could benefit others following this thread or repository and for future reference :+1:

**Comment by ValorNaram** [comment]
#85
