### ISSUE TITLE
Stroller highways

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#30]
Just an issue for the stroller filter that is planned for later, after v.1

Here's an overpass query that is roughly doing what I am talking about:

https://overpass-turbo.eu/s/H7m

**Comment by Discostu36** [comment]
But I'd like to enhance this with additional data. I'd like to use data like `surface=sand`, `wheelchair=no`, `highway=stairs` etc. and paint them yellow for "probably not suited for strollers". The reason for the color should be shown in a popup when clicking on the way.

**Comment by ValorNaram** [comment]
Please consider to not waste your time of e.g. creating issues for features of v.2. Please consider uploading and releasing v.1 for distribution to the user by following the guide on #20 as first and high priority.

Please keep development structure and keep conzentrating on the `privacypolicy.md` file you want to take a look on and then following the guide.

**Comment by ValorNaram** [comment]
This will take some time on the planning of the architecture and I also have a lot of work to do this month.

**Comment by Discostu36** [comment]
In my opinion the rating system is the more important feature. So if you can find the time, please prioritize that one.

**Comment by ValorNaram** [comment]
We agreed not to work on this.**Closing**
