### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#31]
Mobile view of the page has to be fixed: 
- [x] Menu button does not work
- [x] Search bar is cut of
- [x] Links are not visible
- [x] Horizontal and vertical scroll bars are visible

![grafik](https://user-images.githubusercontent.com/30999326/54560395-91cb1780-49c2-11e9-92bd-33545b34ec0c.png)

**Comment by Discostu36** [comment]
- [ ] Still some horizontal scrolling possible (seems to have to do with padding of layermenu)
- [ ] Search does not work

**Comment by Discostu36** [comment]
Doesn't work on iPhone (neither Safari nor Chrome)

I think this has to do with iOS user agent influencing the rendering of the search field. Maybe this can help:
![Datei 20 03 19, 15 38 38](https://user-images.githubusercontent.com/30999326/54693180-7c6efe00-4b26-11e9-8fee-8f17f8520f9e.jpeg)


`input {
    -webkit-appearance: none;
}`

**Comment by ValorNaram** [comment]
Apple should accept the standard and not making its own specification.

This is driving me crazy and at the end we end up in thousand specifications and in ugly code. Internet Explorer's interpretations of code in comments is such a bad specification a developer shouldn't support.

**Comment by Discostu36** [comment]
I don't like it either but the comparison doesn't work. Almost nobody is using Internet Explorer anymore but iPhone/Safari has a market share of 30 %. We can't ignore that.

- [Statistic Browsers](https://de.statista.com/statistik/daten/studie/184297/umfrage/marktanteile-mobiler-browser-bei-der-internetnutzung-in-deutschland-seit-2009/)
- [Statistic Mobile OS](https://de.statista.com/statistik/daten/studie/184332/umfrage/marktanteil-der-mobilen-betriebssysteme-in-deutschland-seit-2009/)

**Comment by ValorNaram** [comment]
But we **can** ignore that since we don't earn money. And certainly we should in order to show that's not an acceptable behaviour.

As more website developers behave like this as more we get Apple to rethink.

**Comment by ValorNaram** [comment]
I will try my best to fix this issue since I accept Chromes existence and having similar problems to get it to work on it.

**Comment by Discostu36** [comment]
The change hasn't solved the problem. Design of the field has changed (inner shadow is gone), but it's still bigger than normal and therefore destroys the layout.

**Comment by ValorNaram** [comment]
It's difficult to solve because I don't have an iPhone

**Comment by Discostu36** [comment]
Ok, I'll try to fix myself when I find the time.

**Comment by Discostu36** [comment]
Only semi-fixed. :-(

![Datei 21 03 19, 23 42 57](https://user-images.githubusercontent.com/30999326/54789590-45d2d980-4c33-11e9-8ce3-711a09239b12.jpeg)
