### ISSUE TITLE
Language system bugs

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#36]
Changing languages after selecting filters still leads to bugs. No high priority, but some day this should work.

**Comment by ValorNaram** [comment]
What kind of bugs?

**Comment by Discostu36** [comment]
I'll have to test again when overpass is working again

**Comment by Discostu36** [comment]
**Steps to reproduce:**

1. Select filters and apply them.
2. Change language


__Expected behavior:__
- The check boxes and markers stay activated 
*or*
- The check boxes and markers disappear


__Actual behavior:__
- The check boxes disappear, but the markers stay. Activate the check boxes again and the markers disappear. Deactivate them again and they appear again.

**Comment by Discostu36** [comment]
One little thing: Overpass query should be resent when changing language. Because otherwise, text in the popups of the already shown markers are still in the wrong language.

**Comment by ValorNaram** [comment]
Why should a user first use Babykartes main functions and then changing its displaying language? This seems unrealistic to me because a user that's not familiar with the language Babykarte presents to him are likely to search for a option to change it and use that function first before he/she comes to the next.

**Comment by Discostu36** [comment]
I once did some beta testing for a computer game. So I'm quite good at trying to do things that nobody would try to do. Best way to find bugs :-)

In other words: You're right, this is very low priority.

**Comment by ValorNaram** [comment]
I did know the bug before but found out that's not worth to work on it.

**Comment by ValorNaram** [comment]
I don't think anymore that this is a bug because it does not influence the Babykarte experience negatively.

Instead it's a feature!
