### ISSUE TITLE
Enhance baby friendliness page in popup

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#38]
Just that I don't forget, some changes I'd like to have in the next version:

- [x]  Entries should be color-coded (yes=green, limited=yellow, no=red)

- [x] Missing tags should be shown, but greyed out

- [x]  Sub-tags should be shown as sub-items

- [x] Description tags should be used (e.g. `stroller:description=Only first floor is accessible`):

The result could look something like this:

![baby_color](https://user-images.githubusercontent.com/30999326/54750526-438f6180-4bd8-11e9-867f-9c2291b2967f.PNG)

**Comment by ValorNaram** [comment]
Need to rethink my algorithm because it is not made for lists

**Comment by ValorNaram** [comment]
Are you sure that you want `No changing table in the men's room` to appear there. Why not just showing the user where he/she can find the changing table?

**Comment by Discostu36** [comment]
Well, there could be a changing table in both rooms (one can still dream). I think it should be made clear if this is not the case.

**Comment by ValorNaram** [comment]
Do you have a POI with a complete dataset for a good baby friendlyness or at least a diaper and highchair or stroller?

**Comment by Discostu36** [comment]
You know it already :-)

https://babykarte.github.io/#19&54.3474881322212&10.140878587917543

**Comment by ValorNaram** [comment]
**Feature request fulfilled, now closing**

**Comment by Discostu36** [comment]
Sorry, I've not been clear enough about this. And I've also changed my mind about some things:

This was mainly meant for restaurants and cafes as a first step (and later as a supplement) to the POI Rating System (#62). 

Also, I now agree with you that this has to be simplified. 

__So this has to be worked on:__
(sorry, this is a bit like "do everything again and completely different")
- [x] Keep the color coding for all POIs
- [ ] The "unknown" state should only be shown in restaurants and cafes (I wouldn't expect a highchair at a doctor's office)
- [ ] Yellow is too hard to read, has to be a bit darker
- [ ] In the rare case of a description (e.g. `diaper:description`, `stroller:description`) there should be an ℹ️ next to the line. The whole line should be a hyperlink. After clicking on it, the description is shown (like popovers in bootsrap)

I now agree with you about the sub tags:
- [ ] [You were right here](https://github.com/babykarte/babykarte.github.io/issues/38#issuecomment-478613550), empty sub tags are not needed
- [ ]  If there are sub tags, the main tag can be left out. So a green "Changing table in the ladies' room" is enough in the above example 

**So above example would look something like this:**
````
<ul>
<li> <span style="color:green">Changing table in the ladies' room</span>
<li>  <span style="color:red">Highchair not available</span>
<li>  <a href="#"><span style="color:orange">Partially stroller friendly ℹ️</span></a>
<li>  <span style="color:darkgrey">Kids area: unknown</span>
</ul>
````

**Comment by ValorNaram** [comment]
>  In the rare case of a description (e.g. diaper:description, stroller:description) there should be an information_source next to the line. The whole line should be a hyperlink. After clicking on it, the description is shown (like popovers in bootsrap)

Need to think about it because it may be not intuitive. Maybe a `details` tag instead of a hyperlink in order to make it more intuitive (wikipedia style).

**Comment by ValorNaram** [comment]
>  If there are sub tags, the main tag can be left out. So a green "Changing table in the ladies' room" is enough in the above example

What is with situations where e.g a fee must be paid, a diaper is also available in the men's restroom etc.?

**Comment by Discostu36** [comment]
You're right, that wasn't thought through enough.

If there is only one sub-tag (or the others are =no), show only this one. If there's more than one positive sub-tag, display main tag with sub-tags beneath like in the original issue.

**Comment by ValorNaram** [comment]
> You were right here, empty sub tags are not needed

And what is with the main tags? Are empty main tags needed?

**Comment by Discostu36** [comment]
Yes, only on restaurants and cafes. To show what kind of information babykarte is tracking

**Comment by ValorNaram** [comment]
> The "unknown" state should only be shown in restaurants and cafes (I wouldn't expect a highchair at a doctor's office)

I've made some modifications. It consists of

- for highchairs
  - Not showing this tag on cafe- and restaurant POIs (`eat`)
- for kids area
  - Not showing for kindergarten- and diaper POIs (`childcare`)

**Comment by ValorNaram** [comment]
> If there are sub tags, the main tag can be left out. So a green "Changing table in the ladies' room" is enough in the above example

It is realistic that a POI has a diaper in the restroom for men too but not instead of?

**Comment by Discostu36** [comment]
Yes:
````
diaper:female=yes 72
diaper:male=yes 21
diaper:female=yes & diaper:male=yes 13

**Comment by Discostu36** [comment]
- [ ] Information with description shouldn't have a larger font size and should stay color-coded
- [ ] Description is shown twice
- [ ] diaper:fee is still there when empty

**Comment by ValorNaram** [comment]
> If there are sub tags, the main tag can be left out. So a green "Changing table in the ladies' room" is enough in the above example

Then changing the main tag to a green "Changing table in the ladies' room" could be a problem when a diaper is also available in the men's restroom

**Comment by ValorNaram** [comment]
> I still like the idea with a pop-over better because it won't extend the list

A popup in a popup is generally a bad idea.

> Information with description shouldn't have a larger font size and should stay color-coded

Colour for description would be always green then.

> diaper=no is shown as unknown (but red)

What do you mean?

**Comment by Discostu36** [comment]
> A popup in a popup is generally a bad idea.

OK, but I really like the ℹ️ :-)

> Colour for description would be always green then.

Why? 
![grafik](https://user-images.githubusercontent.com/30999326/55586664-d2988f80-5729-11e9-8422-6a6d9901a6f7.png)
The grey should be green, the descripiton black
> 
> > diaper=no is shown as unknown (but red)
> 
> What do you mean?

http://localhost:8080/#19&54.33396741701923&10.122873812979378
![grafik](https://user-images.githubusercontent.com/30999326/55586885-5bafc680-572a-11e9-83d2-dc02cb713ca7.png)

**Comment by Discostu36** [comment]
> Then changing the main tag to a green "Changing table in the ladies' room" could be a problem when a diaper is also available in the men's restroom

You're right. Let's not make it too complicated. Keep main and subs.

**Comment by ValorNaram** [comment]
> OK, but I really like the ℹ️ :-)

Sounds reasonable.

**Comment by ValorNaram** [comment]
> Information with description shouldn't have a larger font size and should stay color-coded

Think again? Do you want really annoy your users with different font sizes in the content?

![image](https://user-images.githubusercontent.com/19347636/55588938-5bfe9080-572f-11e9-919d-7ff452340f25.png)

**Comment by ValorNaram** [comment]
>  I think an info-icon is more intuitive than an arrow

The arrow is there to inform the user about that clicking on the text extends information. A info icon alone just indicates the user that the text is an info text which applies to all texts on Babykarte. And in cases where it is a button to click on for help or quick info it is too small for touch devices.

**Comment by ValorNaram** [comment]
> ![grafik](https://user-images.githubusercontent.com/30999326/55586664-d2988f80-5729-11e9-8422-6a6d9901a6f7.png)
The grey should be green, the descripiton black

Where is this place?

**Comment by ValorNaram** [comment]
Found the place

**Comment by ValorNaram** [comment]
Ok now look throw my changes. The following links might help (collected from you during debugging process):

- Restaurant with some data in the baby friendlyness tab: http://localhost:8080/#19&54.33396741701923&10.122873812979378
- POI "Forstbaumschule" with a rich set of data: http://localhost:8080/#19&54.3474881322212&10.140878587917543
- Hospital "Torgau": http://localhost:8080/#19&51.5615645&12.9846290
- Cafè "Liebling" with a rich dataset: http://localhost:8080/#19&54.324401566139166&10.124362438982645
- Diaper with a rich dataset: http://localhost:5400/#18&54.32542770245289&10.12296035874897

**Comment by Discostu36** [comment]
Nice work. Still some suggestions:

1. `diaper:fee` should only be shown when tagged
2. http://localhost:8080/#18&54.32542770245289&10.12296035874897
Bug: `stroller=limited` --> "Location is stroller friendly"
3. Maybe we could make sub-tags also as a drop-down like description. So we have all main information at a glance and all additional information after click
4. I'm still not quite happy with the design of a `<ul>` followed by an arrow. Maybe replace dot with the arrow?

**Comment by Discostu36** [comment]
> > Information with description shouldn't have a larger font size and should stay color-coded
> 
> Think again? Do you want really annoy your users with different font sizes in the content?
> 
> ![image](https://user-images.githubusercontent.com/19347636/55588938-5bfe9080-572f-11e9-919d-7ff452340f25.png)

No I don't and never said so. Read my comment again (and look at my newest commit).

**Comment by ValorNaram** [comment]
**Are you now happy with the results? Validated against #66**

**Comment by Discostu36** [comment]
I'll have a look tonight

**Comment by Discostu36** [comment]
Very nice. But features with additional information now don't stand out as much anymore because now everything's bold. The only difference now is the little arrow. How can we change that? Underline the text? Or revert to only making these bold and not the others?

**Comment by ValorNaram** [comment]
Not everything must be bold. You shouldn't make me to make also the subtags (additional information) bold because I don't recommend it.

Bold symbolizes importance to users. To make all things bold destroys this symbol.

**Comment by ValorNaram** [comment]
Does it look nicer now?

**Comment by Discostu36** [comment]
Yes, but stroller:description isn't shown anymore on this one:

http://localhost:8080/#19&54.32542770245289&10.122927457159678

**Comment by ValorNaram** [comment]
![image](https://user-images.githubusercontent.com/19347636/55955775-93ef6180-5c62-11e9-8009-64c768f48b47.png)

It works for me.

**Comment by Discostu36** [comment]
![grafik](https://user-images.githubusercontent.com/30999326/55956240-c51c6180-5c63-11e9-8510-c5c5ac4dfa2e.png)

Not for me. Do you have unpublished changes?

**Comment by ValorNaram** [comment]
No

**Comment by ValorNaram** [comment]
Can I close this because it works?!

**Comment by Discostu36** [comment]
Yes. Some git issue, had to reset my local branch to solve it.
