### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#40]
Some basic SEO (meta description, keywords) should be added to index.html

**Comment by ValorNaram** [comment]
Keywords and descriptions are discouraged in SEO and nowadays search engines don't relay on them.

**Comment by Discostu36** [comment]
You don't have to lecture me in SEO, it's part of my job :-)

You are right that keywords are not important anymore. But descriptions are shown as part of the Google snippet (the text under the green url) and therefore should explain what the site is about. ([See Google's statement about that](https://support.google.com/webmasters/answer/79812?hl=de))

Also, some facebook-related tags wouldn't hurt (og-image etc.)

**Comment by ValorNaram** [comment]
Good I found someone who could do my work. Now it's your turn to write a appropriate and understandable description.
