### ISSUE TITLE
Shorten URLs

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#41]
Shorten URLs that don't fit into a single line

![Unbenannt](https://user-images.githubusercontent.com/30999326/54825597-48264980-4cae-11e9-8093-1b441af63ee9.PNG)

**Comment by ValorNaram** [comment]
Any suggestion on how to do this?

**Comment by Discostu36** [comment]
I don't know how to program it. Is there a possibility in JavaScript to say "if this line exceeds 35 characters, only print the first 30 and then a ..."?

**Comment by Discostu36** [comment]
Or even ”in case of word wrap...”

**Comment by ValorNaram** [comment]
Why do you want the urls to be shown next to the icons. Why not just displaying the icons?

**Comment by Discostu36** [comment]
Short answer: Every App is doing it that way, it's more intuitive, it's what people expect.
![Screenshot_2019-03-24-09-24-51](https://user-images.githubusercontent.com/30999326/54876837-f0efb880-4e16-11e9-8082-68d91f3f7da6.png)
![Screenshot_2019-03-24-09-24-07](https://user-images.githubusercontent.com/30999326/54876838-f5b46c80-4e16-11e9-8cb3-2416fcd73128.png)

**Comment by Discostu36** [comment]
If it's too complicated to shorten, symbols and text should be in two columns like in the OsmAnd example.

**Comment by ValorNaram** [comment]
For which user experience you hope for by shortening url?

**Comment by ValorNaram** [comment]
Suggestion #2:

For Facebook: Displaying the username next to the Facebook logo.

    Point of Sail Kiel

For email: Don't apply any shortening

For telephone number: Don't apply any shortening

For website addresses: Strip down to domain name

    http://facebook.com
    http://park-klinik.de

**Comment by Discostu36** [comment]
I like the facebook suggestion but I think it does make a difference if a website link does lead to www.supermarket.de or www.supermarket.de/markets/berlin-kreuzberg

**Comment by Discostu36** [comment]
> For which user experience you hope for by shortening url?

Purely aesthetical reasons

**Comment by ValorNaram** [comment]
We should keep thinking about this deeper. 

Making urls short and user friendly is a huge problem in the web since blogging sites like Wordpress turned in.

**Comment by Discostu36** [comment]
I'm not sure if this is worth thinking too deeply about... :-)

I think it'd be easier to keep it as long as it is and add a grid system to make it look it more tidy.

**Comment by ValorNaram** [comment]
Grid system? Could you try to explain what you want, how you want it to look after applying a _grid_?

**Comment by Discostu36** [comment]
https://blog.kulturbanause.de/2013/12/css-grid-layout-module/

Very simple one in this case, just two columns: One for the symbols, one for the text.

**Comment by ValorNaram** [comment]
And how should the grid system help to display the urls tidy? The grid system **does not´** solve the problem of too long urls.

**Comment by ValorNaram** [comment]
Ok I understand what you want but it does not solve the problem of too long urls.

**Comment by ValorNaram** [comment]
**This means this issue stays open**

**Comment by ValorNaram** [comment]
**Feature request fulfilled, now closing**
