### ISSUE TITLE
excluding tags

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#43]
I haven't found out yet how to do this with overpass, but we should add some excluding tags. This means that elements, that do have one of these tags, shouldn't be shown on the map:

- [ ] `access=private`
- [ ] `min_age>=3` (e.g. [this playground](https://www.openstreetmap.org/way/633322207))

Maybe there are more I can't think of right now.

**Comment by ValorNaram** [comment]
Why do you want this? I think its a good idea to keep the request as general as possible so not just parents with babies or 3 >= kids can use Babykarte.

Babykarte will also attract parents with children of age greater than 3 if we have no age conditions. We may add then as a note in the popup as an info which POI has age limitations and which not.

**Comment by Discostu36** [comment]
We already have 13 filters. My fear is that if we extend babykarte (and make it kinderkarte) there will be many more kinds of POIs that could be added to the map and will clutter everything.

**Comment by ValorNaram** [comment]
I don't speak about making it kindergarte.

**Comment by Discostu36** [comment]
Well, the problem is, I don't want parents to go to a playground with their two-year-old and then find out there is no suitable equipment for their child. If I make a map for parents of infants and toddlers, there shouldn't be anything on the map that is only suitable for four-year-olds and older.

If you don't agree, then there is still the question of where to draw the line. I certainly want to exclude restaurants that are only for adults (e.g. because of smoking).

**Comment by ValorNaram** [comment]
>  I certainly want to exclude restaurants that are only for adults (e.g. because of smoking).

I too.

> I don't want parents to go to a playground with their two-year-old and then find out there is no suitable equipment for their child.

We can provide details for age limitations in the POI details view (In the `baby friendliness` tab)

**Comment by Discostu36** [comment]
Sure, but I think most people won't click on that tab when looking for a playground. I do want to use the min_age tag for filtering POIs and 4 years is the only reasonable threshold.

**Comment by mattsches** [comment]
At least think about excluding playgrounds with `access=private`. I've just taken a look at the area where I live and found many "playgrounds" that are actually part of schools or kindergartens.

**Comment by ValorNaram** [comment]
See also #71

**Comment by ValorNaram** [comment]
Pausing this until bug #71 has been fixed.

**Comment by ValorNaram** [comment]
node["leisure"="playground"]["min_age"!~"[0-3]"]({{bbox}});
    way["leisure"="playground"]["min_age"!~"[0-3]"]({{bbox}});
    relation["leisure"="playground"]["min_age"!~"[0-3]"]({{bbox}});

Try this and see if you're happy with the results. See also the interactive example [here](http://overpass-turbo.eu/s/I0V)

**Comment by ValorNaram** [comment]
node["leisure"="playground"]["max_age"!~"[4-9]"]({{bbox}});
    way["leisure"="playground"]["max_age"!~"[4-9]"]({{bbox}});
    relation["leisure"="playground"]["max_age"!~"[4-9]"]({{bbox}});

I think this is what you really want. See also this interactive example [here](http://overpass-turbo.eu/s/I1N)

**Comment by Discostu36** [comment]
No, I don’t care about max age. It’s babykarte, not seniorenkarte 😄

**Comment by ValorNaram** [comment]
I am confused. Can you explain me again in other words what do you want?

What I understood so far:
You want exspecially playground with no equiment for children equal or below 3 years old

**Comment by Discostu36** [comment]
Yes. And therefore, we don't need a filter for max_age but for min_age. Something like this should work:

````
node["leisure"="playground"]["min_age"!~"[4-99]"]({{bbox}});
way["leisure"="playground"]["min_age"!~"[4-99]"]({{bbox}});
relation["leisure"="playground"]["min_age"!~"[4-99]"]({{bbox}});
````

**Comment by ValorNaram** [comment]
Ahh now I understand you.

Did you validated your snippet with overpass turbo and are you happy with the results?

**Comment by ValorNaram** [comment]
# Report for `access!=private`

`access!=private` applies for the following filters. Only those with `access!=private` (meaning: _not private_) will be shown on Babykarte:
- Playgrounds
- Parks

All another filters aren't affected by these changes, so `access!=private`isn't applied to them.

**Comment by ValorNaram** [comment]
> Something like this should work

I prepared an [interactive overpass example](http://overpass-turbo.eu/s/I56) covering the future query Babykarte will send to Overpass now and then. Please validate it with your in-mind view and tell me, if you are happy with the results.

Direct link: http://overpass-turbo.eu/s/I56

**Comment by ValorNaram** [comment]
# Report for `min_age!~"[4-99]"`

`min_age!~"[4-99]"` applies for the following filters. Only those with `min_age!~"[4-99]"` (meaning: _not suited for children under 4 years old_) will be shown on Babykarte:
- Playgrounds
- Parks
- Cafés
- Restaurants

All another filters aren't affected by these changes, so `min_age!~"[4-99]"`isn't applied to them.
