### ISSUE TITLE
More visible loading indicator

### ISSUE THREAD

**Issue by gormo-osm** [babykarte/babykarte.github.io#49]
It would be nice to have a more visible loading indicator that shows whether data is still being loaded from Overpass API. 

I only noticed the progressbar from searching the code for researching the effort to implement a loading indicator. The progressbar does not catch the eye.

I'll try and provide a pull request.

**Comment by ValorNaram** [comment]
> I'll try and provide a pull request.

Against the `devel` branch please.

**Comment by Discostu36** [comment]
@gormo-osm Are you still working on this?

**Comment by ValorNaram** [comment]
He's been committing last at 25th March. See https://github.com/gormo-osm/babykarte.github.io

But we can keep that open, we can merge his changes everytime when he updates his fork accordingly and makes a pull request.

**Comment by ValorNaram** [comment]
**Closed for inactivity**

It's no longer possible to accept and merge pull request for that. It will be just possible, if he updates his code.
