### ISSUE TITLE
Filter ohne Button aktivieren

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#5]
Es sollte möglich sein, die Filter zu aktivieren, ohne eine zusätzliche Schaltfläche klicken zu müssen. Also direktes Absenden der Abfrage, sobald angehakt wird.

**Comment by ValorNaram** [comment]
Are you sure you want to have this function? On the move Babykarte should take as little as it can of the user's internet flatrate. Just sending one request with two queries in it saves mobile data.

If you want it, I will implement a 'data save' mode in order to give the user more control of his/her mobile data usage. Or sending the query to Overpass right after a click action on the filters.

**Comment by Discostu36** [comment]
Ok, you're right.

**Comment by Discostu36** [comment]
Comment by -karlos- about this:

„Das “Apply Filter” ist auch leicht zu übersehen, selbs wenn es fett wird. Besser gleich oder wenn 1s lang nichts geändert wird automatisch aktuallisieren?“

maybe we should reconsider?

**Comment by ValorNaram** [comment]
> Are you sure you want to have this function?

It is funny. It seems to be more intuitive to update the filters without a click on a button.

**Comment by Discostu36** [comment]
Even with bigger queries the data coming from overpass only has about 20kb.  So I don't think that we have to take that into consideration. I think an automatic sending of the query after 1 second is a good idea.

**Comment by ValorNaram** [comment]
As a reminder you made me to make this button and to stop the automatic loading of filters.

Why after 1sec instead of immediately?

**Comment by Discostu36** [comment]
> As a reminder you made me to make this button and to stop the automatic loading of filters.

Did I? Don't remember. My first post in this issue doesn't sound like it...

> Why after 1sec instead of immediately?

Well, it's some sort of middle ground between the two possibilities: I don't have to click a button. But if I want to quickly mark two or three filters, it doesn't already send a query after the first one.

But an important question to consider is: What do we do in mobile view? Do we need an `x` to close the filter list after making the changes?

**Comment by ValorNaram** [comment]
> Do we need an `x` to close the filter list after making the changes?

No!

**Comment by Discostu36** [comment]
OK, so you think it's intuitive that users have to click the menu button a second time? I'm not sure about that, but we can try it that way.

**Comment by ValorNaram** [comment]
Don't you use a websites on mobile devices and don't you ever use a menu button on mobile devices to close and open the website menu?
