### ISSUE TITLE
addr:street bug

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#52]
addr:street isn't always correctly parsed. Maybe a problem with `ß`?

`addr:street=Schloß Nymphenburg`

![undefined](https://user-images.githubusercontent.com/30999326/54930215-2d0a4280-4f17-11e9-888e-f8e9a5926155.PNG)

**Comment by ValorNaram** [comment]
Nominatim has no entry with name `street` for that POI

**Comment by Discostu36** [comment]
Yes, it does.

https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=16125284&class=amenity
