### ISSUE TITLE
"Edit in OSM" opens wrong area

### ISSUE THREAD

**Issue by Flying-Duck** [babykarte/babykarte.github.io#53]
Pressing the Popups "Edit in OSM" opens a window at www.openstreetmap.org, containing my last seen area. This one is loaded to JOSM, not the area around the selected POI.

**Comment by Discostu36** [comment]
I've opened an issue at ID Editor for that

https://github.com/openstreetmap/iD/issues/6106

@ValorNaram Can we add the coordinates to the edit link?

**Comment by ValorNaram** [comment]
If we pass the coordinates to the url, the POI the user wants to edit won't be selected anymore. We have to wait for a fix in iD

**Comment by Discostu36** [comment]
Are you sure? This link seems to work for me.

https://www.openstreetmap.org/edit?way=16125284#map=20/48.15929/11.49979

**Comment by ValorNaram** [comment]
Thought it doesn't work. Yes, I correct my previous comment and say, yes it is possible to do that with just the coordinates.

**Comment by Discostu36** [comment]
@Flying-Duck I can't reproduce the error. Can you explain in which cases the link doesn't work correctly?

**Comment by Flying-Duck** [comment]
I open "https://babykarte.github.io", select any category, click the link and it happens.
BUT
I can say it depends on my OSM settings. Changing my default editor from JOSM to iD and the link works as intended. So it seems to be a problem with the comunication to JOSM.
