### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#55]
Some user may want a user manual/guide for how and what the user can use Babykarte.

Some suggestions:
- [x] Displaying a note to introduce users to the filter menu (bar)
- [x] ~~Implementing a "Trash" button in the filter menu for fast clearing of selected filters (unselecting all selected filters)~~ A button `(de)select all filters` has been added to Babykarte
- [ ] Displaying a small introduction and or link to the guide HTML page for introducing the filters and other Babykarte stuff.

**Comment by Discostu36** [comment]
I've struck two of he four suggestions because I'm not of the opinion anymore that they are necessary. But there definitely should be some sort of "Help" button with a little text. I'll write that text when I find the time.

**Comment by ValorNaram** [comment]
Or we wait and prove our skills in making something intuitive

**Comment by ValorNaram** [comment]
See also #68
