### ISSUE TITLE
Extend Paediatricians 

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#56]
Filter should be extended to "Doctors and hospitals" ("Kinderärzte und -krankenhäuser"). Query should only be `healthcare:speciality=paediatrics`

**Comment by Discostu36** [comment]
Even better: 
`healthcare:speciality~paediatrics` 

Because hospitals will often have a list of specialities.

e.g.:
 `healthcare:speciality=general;internal;paediatrics;radiology;surgery;gynaecology;ophthalmology;otolaryngology`

**Comment by ValorNaram** [comment]
And what should we do with the first filter `Paediatricians`?

**Comment by Discostu36** [comment]
I'm talking about the first filter. It should be extended, so that it not only contains doctors.

**Comment by ValorNaram** [comment]
Babykarte now has the infrasstructure to fulfill this request.

**Comment by ValorNaram** [comment]
Can you provide a position on the world map on which I can test this feature?

So a place with an hospital with this tagging or tagging list as you mentioned.

**Comment by Discostu36** [comment]
https://www.openstreetmap.org/way/25009784
https://www.openstreetmap.org/node/26601595
