### ISSUE TITLE
Changes to use of location

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#57]
[-karlos-](https://www.openstreetmap.org/user/-karlos-) has also given some feedback about the user's location:

1. Babykarte shouldn't ask for the user's location when (s)he's using an url containing lat/lon. When I'm clicking on [this link](https://babykarte.github.io/#16&48.56963&13.45554), I want to see that area, not my own location
2. He also wrote that in his opinion the website should only ask for location after the user has clicked on a special button for that. 

I certainly agree with 1 and I tend to also agree with 2. When visiting osm.org or Google Maps, they also only ask for my location after I've clicked on a button.

**Comment by ValorNaram** [comment]
I will fulfill this request at weekend or today evening.

**Comment by ValorNaram** [comment]
Request fulfilled

**Comment by Discostu36** [comment]
Please make sure that the icon doesn't overlap with layermenu in mobile view.
