### ISSUE TITLE
Loading indicator in mobile view

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#58]
In certain circumstances the loading bar stops the middle of the screen when first visiting the website:

- mobile view (doesn't have to be on mobile device, small viewport is enough)
- decline usage of location

**Comment by ValorNaram** [comment]
This is a technical problem.

You know that language files are loaded asyncronously and a function takes use of data from language files that are not loaded onto the code beforehand. So this function raises an error execption preventing the browser from ending execution of code block.

**Comment by Discostu36** [comment]
OK, I don't understand. But that's not important. Important is: Can you fix it? :-)

**Comment by ValorNaram** [comment]
Yes, I could fix it easily because I solved #57

**This issue does not seem to be up to date anymore because it was fixed
