### ISSUE TITLE
baby_feeding

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#61]
I have ignored the baby_feeding tag until now because it is very rarely used. But there seem to more and more places with special rooms or chairs for mothers to feed in, so I think this should somehow be a part of babykarte. 

I don't think we need a special filter and I also don't want to clutter the baby friendliness tab even more. So I think this is the best way:
- Show in baby friendliness tab when used and `!=no`
- Don't show as "unknown" when not used

**Comment by ValorNaram** [comment]
No documentation found for `baby_feeding'? Is this tag implemented or approved by a proposal?

**Comment by Discostu36** [comment]
https://wiki.openstreetmap.org/wiki/Proposed_features/babycare#Baby_feeding
https://taginfo.openstreetmap.org/keys/baby_feeding

**Comment by Discostu36** [comment]
This doesn't work yet. There are no entries in the language files, but I'm not sure this is the only reason.

**Comment by ValorNaram** [comment]
oh yeah I forgot them:

    "PDV_BABYFEEDING_YES": "Babycare possible",
    "PDV_BABYFEEDING_NO": "Babycare impossible",
    "PDV_BABYFEEDING_ROOM": "Seperated room for babycaring",
    "PDV_BABYFEEDING_MEN_YES": "Babycare possible also for men",
    "PDV_BABYFEEDING_WOMEN_YES": "Babycare possible for women",
    "PDV_BABYFEEDING_MEN_NO": "Babycare not possible for men",
    "PDV_BABYFEEDING_WOMEN_NO": "Babycare impossible for women"

Put this at the end of the json in the two files `de.js` and `en.js`

JSON are the objects defined between `{` and `}` (curly brackets)

**Comment by ValorNaram** [comment]
**`baby_feeding` wasn't officially approved and still under way as of 2013.**

@Discostu36 Do you want to make this proposal alive and restarting the discussion on it, moderating, cleaning up... etc?

**Comment by Discostu36** [comment]
There is much that could be improved about it but I don't have the time to think about a better tagging scheme and discuss this etc
