### ISSUE TITLE
Caching issue?

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#65]
There are caching(?) problems when a POI fits for two filters.

Steps to reproduce:
1. Focus map on an cafe that also has a diaper tag (e.g. [this one](http://localhost:8080/#19&54.324401566139166&10.124362438982645))
2. Select cafe filter
3. Deselect cafe filter
4. Select diaper filter
5. Cafe is not shown

**Comment by ValorNaram** [comment]
> 5. Cafe is not shown

It is shown on the map but overlapped by the marker for the diaper

**Comment by Discostu36** [comment]
No, what I meant is that it is not shown as diaper. Seems like diaper marker is overlapped by hidden cafe marker or something like that.

**Comment by ValorNaram** [comment]
the other way around. Diaper marker (grey) overlapps the café marker (purple)

**Comment by ValorNaram** [comment]
> There are caching(?) problems when a POI fits for two filters.

Definitely no. It has nothing to do with caching but how filters are handled. This is a decision making problem which isn't easy to solve.

**Comment by Discostu36** [comment]
I'm still not sure we're talking about the same thing. But it doesn't matter because I can't reproduce it anymore.
