### ISSUE TITLE
Create a JOSM preset

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#72]
I'd like to create a JOSM preset (that can also be used in Vespucci) including all tags from the "baby friendliness" tab. This way users can easily add information to the babykarte without having to memorize keys and values.

Related links:
https://josm.openstreetmap.de/wiki/TaggingPresets
http://vespucci.io/tutorials/presets/

**Comment by ValorNaram** [comment]
Are you able to do this on your own? I am beginner user of JOSM and Vespucci doesn't work for me.

**Comment by ValorNaram** [comment]
For every filter an own preset? This solution seems best to me.

**Comment by Discostu36** [comment]
I'll try to do this on my own. I'm not sure yet if one or more filters.

**Comment by ValorNaram** [comment]
Do you have an update?

**Comment by Discostu36** [comment]
**Status:** I've started to create a preset for changing_table

**Comment by Discostu36** [comment]
Should we host these in the JOSM wiki (as recommended by JOSM) or in this repository?

**Comment by ValorNaram** [comment]
I suggest hosting in the JOSM wiki and linking to it inside this repo

**Comment by Discostu36** [comment]
**Status:**
I've finished the presets for Changing tables and high chairs. 


**Still to do:**
- [ ] Stroller
- [ ] Kids area
- [ ] Icons
- [ ] Test Vespucci compatibility

I will upload to the JOSM Wiki when it's done. Here's the current status:

````
<?xml version="1.0" encoding="UTF-8"?>
<presets xmlns="http://josm.openstreetmap.de/tagging-preset-1.0" author="Discostu36" version="1.[[revision]]_[[date]]" shortdescription="Baby friendliness" de.shortdescription="Babyfreundlichkeit" description="Tags indicating the baby friendliness of a POI" de.description="Tags, die die Babyfreundlichkeit eines Ortes beschreiben">
    <group name="Baby friendliness" de.name="Babyfreundlichkeit" icon="">
        <item name="Changing tables" de.name="Wickeltische" icon="">
            <label text="Information about the presence of changing tables." de.text="Informationen über das Vorhandensein von Wickeltischen." />
            <space />
            <combo key="changing_table" text="Changing table(s):" de.text="Wickeltisch(e):" values="yes,no,limited" />
            <combo key="changing_table:count" text="Count" de.text="Anzahl" values="1,2,3,4,5" />
            <check key="changing_table:fee" text="Fee" de.text="Gebühr" />
            <combo key="changing_table:location" text="Location" de.text="Ort" values="female_toilet,male_toilet,unisex_toilet,wheelchair_toilet,room,dedicated_room,sales_area" />
            <text key="changing_table:description" text="Description" de.text="Beschreibung" />
            <preset_link preset_name="High chairs" />
        </item>
        <item name="High chairs" de.name="Hochstühle" icon="">
            <label text="Information about the presence highchairs." de.text="Informationen über das Vorhandensein von Hochstühlen." />
            <space />
            <combo key="highchair" text="High chair(s):" de.text="Hochstühle:" values="yes,no,1,2,3,4,5" values_sort="false" />
            <text key="highchair:description" text="Description" de.text="Beschreibung" />
            <preset_link preset_name="Changing tables" />
        </item>
    </group>
</presets>

````

**Comment by Discostu36** [comment]
The first version has been published:

https://josm.openstreetmap.de/wiki/Presets/Baby_friendliness

Icons are still missing and it hasn't been optimized for Vespucci yet. But it does work.

**Comment by ValorNaram** [comment]
Did you get further?

**Comment by Discostu36** [comment]
I've given up on Vespucci. Only Icons are still missing.

**Comment by ValorNaram** [comment]
What sorts of icon do you need?

**Comment by Discostu36** [comment]
Very simple ones, the babykarte icon used here as main icon for the template, then icons for changing_table, highchair, kids_area (a ball?) and stroller.

**Comment by ValorNaram** [comment]
I can make these icons. I love adventures.

**Comment by ValorNaram** [comment]
What about thes icons?

![changingtable svg](https://user-images.githubusercontent.com/19347636/62653101-22e46000-b95d-11e9-9986-1ec5e190fb72.png)
![highchair svg](https://user-images.githubusercontent.com/19347636/62653102-22e46000-b95d-11e9-9c24-e540343b860b.png)

**Comment by Discostu36** [comment]
I like the simplicity color wise, but I think the first image is too detailed when displayed in JOSM (only  32×32 or something like that). If you're interested, you could download the preset, add the icons locally and test how they look in JOSM (and post screenshots here).

**Comment by ValorNaram** [comment]
![Screenshot from 2019-08-08 18-18-10](https://user-images.githubusercontent.com/19347636/62719845-23d2cb80-ba09-11e9-8c14-78e8ff63695e.png)

Icons optimised. I miss the subpresets for `kids_area` and `stroller`

**Comment by carstenhag** [comment]
Hey, just tested the zip link for Vespucci and it works fine. It doesn't show an icon though for the 4 elements.

**Comment by Discostu36** [comment]
@ValorNaram Looking good. I don't know why the sub presets don't show for you, they did for me when I last tested.

@carstenhag Icons are not online yet.

**Comment by ValorNaram** [comment]
>  I don't know why the sub presets don't show for you, they did for me when I last tested.

I know why but we have another problem. JOSM supports just absolute file paths or relative to JOSMs internal icon set. JOSM does not support file paths relative to the preset location path.

Will JOSM support relative file paths if we serve our preset in zip format?

**Comment by Discostu36** [comment]
https://josm.openstreetmap.de/wiki/Styles#Icons

**Comment by ValorNaram** [comment]
![Screenshot from 2019-08-09 18-17-08](https://user-images.githubusercontent.com/19347636/62793557-1b929300-bad2-11e9-926a-3a358c89d018.png)

Now I have these. Do I have access to JOSMs' preset database for uploading?

**Comment by Discostu36** [comment]
Please also add the babykarte icon to the preset top level. Afterwards, you can just edit the wiki page linked above.

**Comment by ValorNaram** [comment]
> Afterwards, you can just edit the wiki page linked above.

**Done!** I also uploaded it [here](https://github.com/babykarte/babykarte.github.io/files/3488707/Presets_Baby_friendliness-preset.zip)

**Comment by ValorNaram** [comment]
https://github.com/carstenhag Now it's online, you can find it [there](https://josm.openstreetmap.de/wiki/Presets/Baby_friendliness) and the direct download link is [this one](https://josm.openstreetmap.de/josmfile?page=Presets/Baby_friendliness&zip)

**Comment by Discostu36** [comment]
You have to upload the images to the wiki page, not the zip file. Like in [this preset](https://josm.openstreetmap.de/wiki/Presets/caravan_site). The zip is created automatically.

**Comment by ValorNaram** [comment]
I hate automatic systems

**Comment by ValorNaram** [comment]
> You have to upload the images to the wiki page

**Done**

**Comment by carstenhag** [comment]
![Screenshot_20190810-224416](https://user-images.githubusercontent.com/3776997/62826716-7e625800-bbc0-11e9-9992-548b368e7f07.jpg)

After updating the preset, the images now show up. Thanks!
