### ISSUE TITLE
translations ... 

### ISSUE THREAD

**Issue by fredao** [babykarte/babykarte.github.io#73]
Hi Michael ... - if there is a simple possibility, I offer you translations into the languages spoken in our project.  https://wiki.openstreetmap.org/wiki/EuYoutH_OSM#Possible_Logos ... In a former project, we started the translation for graphhopper ... with a simple spreadsheet https://wiki.openstreetmap.org/wiki/EuYoutH_OSM#Possible_Logos ... if that fits for you, I start the spreadsheet, you deliver me the words you need and I care about the translations ;-)

**Comment by fredao** [comment]
feel free to put your DE and EN words into the spreadsheet ;-) ... In the first step I deliver EN, ES, PT, RO only - a lot of the other translators I know as well ... but that would be the second step ;-)

**Comment by ValorNaram** [comment]
And how we could transfer it to Babykarte?

Another problem: According to law we would also have to translate the privacy policies and keeping them up to date.

**Comment by fredao** [comment]
@ValorNaram so you ask me?

**Comment by ValorNaram** [comment]
## Introduction

Currently we store the language reference of a specified language in the `js` folder. For the German language the file `js/de.js` is the responsible one. For the English language the file `js/en.js` is the responsible one. Ones invoked by Babykarte it loads its data and sets the lang id (The lang it is always the language code) so Babykarte updates its user interface.

## Problem 1
Your spreadsheet uses the excel format and contains more than one language reference. This is what we had before but we decided to save disk- and mobile data usage and therefore to put each language in its own file. When we use your spreadsheet, we have to seperate each language column into its own language js file and to convert it into JSON.

## Problem 2
We have a privacy policy. @Discostu36 said Babykarte, which doesn't save or process personal data, needs a privacy policy, so we have one like the GDPR specified. The privacy policy needs to be translated into each language seperately. It's means a heavily burden to translators to translate the privacy policy and to keep it up to date. Michael and I had a controversial discussion about the need of a privacy policy a long time ago. It seems Europe doesn't like community projects and therefore tries everything to prevent the outcome of such projects.

## Conclusion
Implementing your idea of taking the spreadsheet from GraphHopper and then adapting it to our needs including the development process of a converter is of course technically no problem (=possible) but the effort I need to put in (developing converter) and making it possible to keep translations up to date is quite heavy. For every update of a language reference I need to run the converter and to upload the results manually.

The solution we have now is the best fitting one and not hard to maintain and keeps the data usage as low as possible for our users. But at first we need to write a tutorial on how to add a language to Babykarte. Currently we haven't written such a tutorial yet but we're working on it and looking forward to upload such tutorial one day.


But thank you for your great offer. We appreciate that.


SITE NOTE: Babykarte is powered by javascript (currently no server side scripting possible)
