### ISSUE TITLE
Changing tables accessible for men

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#75]
In a discussion on the tagging mailing list, Kevin Kenny has written this interesting comment:

> In any case, thinking back a quarter-century or so to when my daughter
was a baby, the key question in my mind was usually, "is there a
changing table that isn't in the ladies' room?'  At the time, places
where a man could change a diaper discreetly were almost vanishingly
rare.

So my question is: Should we add a sub-filter for diaper, to only show changing tables on the map  that are accessible for men?

**Comment by ValorNaram** [comment]
Do you want one more entry in the list of filters?

**Comment by Discostu36** [comment]
I think it'd be better to have it some kind of sub-filter. At least indented a bit, maybe only visible after click (like in baby friendliness tab). I'm not sure yet, not quite happy with any solution I come up with.

**Comment by ValorNaram** [comment]
> [...] like in baby friendliness tab [...]
I wouldn't recommend using the "details" element or similiar approach for this. User are likely to click on the main filter rather on the sub filter. This isn't user friendly

**Comment by Discostu36** [comment]
Maybe the sub-filter could appear as soon as the main filter is checked? As a possibility of further filtering?

**Comment by Discostu36** [comment]
This query seems to work:

https://overpass-turbo.eu/s/Ipz

**Comment by Discostu36** [comment]
The query would have to look something like this (not a real query, just that you get the idea):

1. Show all `(diaper:male=yes|diaper:unisex=yes|diaper:wheelchair=yes|diaper=room|diaper=bench)`
2. Show all (`diaper=yes|diaper~[0-9]) AND diaper:female!=yes `

**Comment by ValorNaram** [comment]
> Maybe the sub-filter could appear as soon as the main filter is checked?

Users don't want to click on a filter they don't want to use in order to be able to activate what they really want (activating the sub filter). Men won't click on the main filter to load unnecessary data they don't want in order to be able to activate the subfilter which conveys them the information what they want. If I were you I wouldn't work with main- and sub filters because it's not intuitive here. I suggest to treat it simply as a normal filter.

**Comment by Discostu36** [comment]
OK, let's do it like that.But how to name them?
[ ] Changing tables[ ] Only changing tables accessible for men
Or different?
Also, it shouldn't be possible to select both.
Or, to avoid overlap:
[ ] Changing tables accessible for women[ } Changing tables accessible for men

**Comment by ValorNaram** [comment]
- [ ] Changing tables
- [ ] Only changing tables accessible for men

 **or**

- [ ] Changing tables accessible for women 
- [ ] Changing tables accessible for men

**Comment by ValorNaram** [comment]
@Discostu36 Could you please check, if my changes are working. You might know best where the good datasets are. I'll try myself via overpass.

**Comment by ValorNaram** [comment]
Closing this because my changes were reviewed.

**Comment by Discostu36** [comment]
Please look again at my suggestion [above](https://github.com/babykarte/babykarte.github.io/issues/75#issuecomment-487914361). At the moment, changing tables are only shown when `diaper:male=yes` and `diaper:unisex=yes` is used. But as I wrote there are some more cases that need to be included. I'm just not sure how to write the query.

**Comment by Discostu36** [comment]
This seems to work:

https://overpass-turbo.eu/s/IUb

**Comment by ValorNaram** [comment]
Please see the description for [diaper=bench](https://wiki.openstreetmap.org/wiki/Key:diaper)

**Comment by ValorNaram** [comment]
**`diaper=room` added to query.**

**Comment by Discostu36** [comment]
> Please see the description for [diaper=bench](https://wiki.openstreetmap.org/wiki/Key:diaper)

What are you getting at? That the bench might be in the ladies' room? Then it has to be moved to the second query.

**Comment by ValorNaram** [comment]
No, I mean diaper=bench isn't relevant for this query because it's not men specified, unisex specified nor gender neutral.

**Comment by Discostu36** [comment]
OK, we were tackling this from different ends. My idea was to show all POIs where it is not explicitly stated that the changing table is in the ladies' room. Your idea was to only show POIs where it is explicitly stated that the changing table is not in the ladies' room. 

Maybe your approach is better. But I think we should also include `diaper:wheelchair=yes` because in my opinion this is most often used as "It's in the toilet for wheelchair users" (and therefore can be also accessed by men), not "It's accessible with a wheelchair".

**Comment by ValorNaram** [comment]
Ok let's do it like you've had said
