### ISSUE TITLE
Unknown missing from baby friendliness

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#83]
Somehow the "unknown" entries have disappeared from the baby friendliness tab. I think these are useful to show users what information still needs to be added. Please restore (for all tags except baby_feeding)

**Comment by ValorNaram** [comment]
![Screenshot-2019-6-1 Babykarte - Der Stadtplan für Eltern von Babys und Kleinkindern](https://user-images.githubusercontent.com/19347636/58746844-61443700-8463-11e9-858d-6c98681204da.png)

**Done**
