### ISSUE TITLE
Adding support for key "changing_table"

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#85]
The approval of the proposal on https://wiki.openstreetmap.org/wiki/Proposed_features/changing_table is close. So I am opening this issue by myself and set this to high priority.

This proposal intends to replace the current active tagging scheme [diaper](https://wiki.openstreetmap.org/wiki/Key:diaper) which did not go through a proposal process.

**Comment by Discostu36** [comment]
OK, just to make sure: We'll continue to support the then deprecated key, don't we?

**Comment by ValorNaram** [comment]
Yes, the support for "diaper" will persist. Both will co-exist until the Key "diaper" is not used anymore.

**Comment by ValorNaram** [comment]
STATUS: **Waiting for the end of voting process**

The vote will be closed on Wednesday.

**Comment by ValorNaram** [comment]
STATUS: **Proposal has been approved. Feature page has been written. Waiting for response from the community**

See the corresponding [proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/changing_table) and take also a look on its friendlier [feature page](https://wiki.openstreetmap.org/wiki/Key:changing_table)

**Comment by Discostu36** [comment]
I think this should be released as soon as it's ready. I've moved it from v.3.0 to v.2.1.

**Comment by ValorNaram** [comment]
**Happy testing**

Don't have time to test it with all use cases.

**Comment by Discostu36** [comment]
Changing tables in ladie's room visible in filter for men.

http://localhost:8080/#15&54.31301849614071&10.111624718410896

![grafik](https://user-images.githubusercontent.com/30999326/59555812-f7767200-8fb8-11e9-86f6-aad2add89d3e.png)

**Comment by carstenhag** [comment]
Hey, `changing_table` should be added to https://taginfo.openstreetmap.org/projects/babykarte#tags and to https://wiki.openstreetmap.org/wiki/Babykarte.

The only mentions there are `diaper`, which is deprecated.

**Comment by ValorNaram** [comment]
@Discostu36

**Comment by ValorNaram** [comment]
> Hey, changing_table should be added to https://taginfo.openstreetmap.org/projects/babykarte#tags and to https://wiki.openstreetmap.org/wiki/Babykarte.
> 
> The only mentions there are diaper, which is deprecated.

We have the issue #39 which is better suited for such comments. Future comments about the wiki should go there.

**Comment by Discostu36** [comment]
I've added it to #39 and will open a new issue for the Taginfo file.
