### ISSUE TITLE
Prefer other filters over diaper

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#86]
**Test situation**
- A restaurant has a diaper key
- I select the restaurant filter and the diaper filter

**What happens**
- A diaper marker is shown at the location

**What should happen**
- A restaurant marker is shown at the location

**Possible fix**
- Give the diaper filters a lower priority than the other filters.
- Maybe this can be most easily accomplished by moving them to the end of the list

**Comment by ValorNaram** [comment]
Could you provide a list like this

1. Restaurants
2. Cafés
3. Changing tables
4. Changing tables accessible for men
...

so I know which filter you want to priorize and which not. Create a ranking.

**Comment by ValorNaram** [comment]
I am suggesting

1. All other filters
2. Changing tables accessible for men
3. Changing tables

**Comment by Discostu36** [comment]
I agree
