### ISSUE TITLE
Adding "Playground features" to baby friendliness tab

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#88]
> If a leisure=playground has tags with the scheme playground:*=yes, these should be added to the baby friendliness tab under a heading "Playground features:"

Taken from #84 and https://github.com/babykarte/babykarte.github.io/issues/84#issuecomment-501444251

**Comment by ValorNaram** [comment]
STATUS: **Waiting for #85 to be closed and v.2.1 of Babykarte to be released**

**Comment by ValorNaram** [comment]
We can now work on this issue

**Comment by ValorNaram** [comment]
Please look through https://github.com/babykarte/babykarte.github.io/commit/b8bcdc39a5c6bc6022501d3b2b0d9cd7e9a99e52 and modify it according to the tags you want Babykarte to process in the baby friendliness tab. You don't see anything in the tab right now because I didn't define the text to display to the users yet.

**Comment by Discostu36** [comment]
I've edited it, so we only have those tags that are used 100 times or more.

**Comment by ValorNaram** [comment]
Ok. Now you can alter the text (if needed). You can also test this feature right now in the development version (local) and see how it works. **It works, I tested four of the entries.**

**Comment by Discostu36** [comment]
I will have a look at it tomorrow evening.

**Comment by Discostu36** [comment]
Good work. 

I think we should remove the missing information about changing tables etc. from these:
![grafik](https://user-images.githubusercontent.com/30999326/59915041-024b5f80-941c-11e9-9c05-8c28693204f3.png)

Actually, I think that it might be best to show the "unknown" texts for cafes and restaurants only.

**Comment by ValorNaram** [comment]
**Done**
