### ISSUE TITLE
Deleting the file for using google's search console

### ISSUE THREAD

**Issue by ValorNaram** [babykarte/babykarte.github.io#89]
You might know that I truly hate the file at https://github.com/babykarte/babykarte.github.io/blob/master/googlee9b768697fce2a11.html and my developer console shows that my browser opens a google url when I click on (It's common practice among search engine providers and advertising/spying-on-users/gathering-user-data industry)

![Screenshot-2019-6-16 babykarte osm - Google-Suche](https://user-images.githubusercontent.com/19347636/59561417-4efbf880-9020-11e9-9507-de1ecacb41a3.png)

I am talking about the google url https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwii0debyO3iAhUOIlAKHSx4B0MQFjACegQIBxAB&url=https%3A%2F%2Fbabykarte.github.io%2F&usg=AOvVaw0xZUOz3YZ2UCaLCxRBawpk which does not tell us for which purpose is it for. We know that the tracking industry uses intransparency to hide from us what they want and what they already know from us. Google uses this url to track the click and this track shows up or can be shown in Google's search console and brings the page visits count up. Google also stores the timestamp and shows it in search console so the administrator knows the time and date of the users' click.

This is mechanism there's no need to use cookies which users can control, edit and most importantly delete. The url from the link above uses web1.0 technology on the client site to store the users click data like timestamp, search result etc. on google servers making these data available in the search console.

Do we want to support a mechanism that is used to hide tracking activities and adds extra intransparency in a intransparent world?

**Simple question: Can we delete the file because I think Google won't delete the search results directing users to the Babykarte even if they don't find the file anymore?** We can try it without it and add it back when we notice a change in Google's behaviour in indexing Babykarte.

Just for completing this issue:

![Screenshot-2019-6-16 Ecosia - the search engine that plants trees](https://user-images.githubusercontent.com/19347636/59561613-c0d54180-9022-11e9-946a-10b0ae434fe3.png)

The entry 'Babykarte' shows up in Ecosia search results (powered by Microsoft Bing) even without the need of an extra file from Microsoft in our repository.

**Comment by Discostu36** [comment]
- Google does collect this data anyways. The kind of link you pasted above is used for every Google result. It has nothing to do with Search Console. 
- The file that I uploaded to the repo has only one function: It proves to Google that I'm the owner of the website. This leads to Google sharing a small part of their data with me. This way I can see what search terms lead visitors to our website (if at all).
- The files does not lead to any additional data being collected (if it did, I would have to write it into the privacy policy)
- Deleting the file won't change anything about Google's data. It will only change if I can use the Search Console or not.
- If users don't want Google to collect data about them, they shouldn't use Google.

**I don't see a rational reason for deleting the file. But if its existence can in any way keep you from continuing your work on the project, I will delete it.**

**Comment by ValorNaram** [comment]
> This way I can see what search terms lead visitors to our website (if at all).

If you want to know which search terms visitors used or likely to use just ask me. You just need to step in into the shoes of your visitors or someone else visiting your site. No data collection needed there and I also do some tests with search engines to check which search terms users are likely to enter to get a map for parents.

You just need to step in into shoes of someone else.

**Comment by Discostu36** [comment]
This has nothing to do with empathy but with SEO. We had only 2 visitors from Google since Babykarte exists. This value we cannot get with empathy but only with statistics.

And I know that I'm repeating myself, but: We do not have any influence in this data being collected or not.

**Comment by ValorNaram** [comment]
Yes, I know. Of course you don't get the values via empathy but you are also a user and you know which search terms users are likely to use

**Comment by Discostu36** [comment]
By the way: I can give you (or other contributers who are interested) access to the data if you have a Google Account. This way you can see that this is really quite harmless and no "tracking" as you stated in your original posting.

**Comment by ValorNaram** [comment]
Not needed at least for me. I trust you. My question is how google's search console helps us to reach more people? I personally think that knowing how many people are finding us via google isn't helpful

**Comment by Discostu36** [comment]
Well, it's helpful in that it's telling us that there's much to do in the field of SEO if we want to get Babykarte known outside of the OSM community. And if we'd work on that, we could see if our efforts are making Babykarte more visible. But as I at the moment don't really want to spend time working on that, I might just as well delete the file now and reinstate it when needed.
