### ISSUE TITLE
fix french layout

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#96]
Because of the long string for the privacy policy, the layout of the layermenu breaks in the French view. 
![Bildschirmfoto](https://user-images.githubusercontent.com/30999326/60389084-b5baf080-9abb-11e9-9cbd-5a9e0ccc6715.png)

Maybe the easiest way to fix this would be to put the language selection into a single icon
<img src="https://image.flaticon.com/icons/svg/61/61027.svg" width="75px" /> 
After click, a language list could open (vertical menu).

**Comment by ValorNaram** [comment]
I know this bug and I am working on a redesign of the bar. Actually I think your suggestion is very good. Like the icon because I have had the problem of choosing the right icon for the language bar dropdown (vertical list)

**Comment by NicolasGrosjean** [comment]
There is also issues with the bar on a smartphone : 

- There is no margin between the menu button and the search bar
- The string of the menu is not in the language and so are not translated

![image](https://user-images.githubusercontent.com/13560473/60394862-d2dad800-9b2a-11e9-811c-dfac4e66899c.png)

The menu text should be replace by a [menu icon](https://icons8.com/icon/3095/menu).

**Comment by ValorNaram** [comment]
This is because the text wraps wrong.

Seems that I forgot to translate the `alt` text of the images we use for Babykarte

**Comment by NicolasGrosjean** [comment]
Sorry, I am a noob, I have not seen you have already put an image.

In fact I have replaced `'/` by `'` in the index.html file to open it in a web browser but I have forgotten to replace `"/` by `"` so the menu image was not loaded.

I have seen on some screenshots and messages that you serve the website on the localhost but I have not found on this repository how to do. It should be useful to put the way in the Readme or Contributing file.

P.S : We can maybe switch in another issue for this because it is no more related to the menu.

**Comment by ValorNaram** [comment]
Yes, Michael and I use a lightweight debugging server that we both serve to "http://localhost:8080" so we can exchange links to the debugging version of Babykarte. This allows Michael to point me in the right direction and this method Michael has been enabled to describe the bug he encountered/feature he wants interactively. An exchanging workflow I invented to speed up communication.

Yes, of course. I can do a tutorial how to activate the lightweight debugging server for your system. Happily you just need the default operating system to be installed on your system. The lightweight debugging server we use has been bundled within python3 and python3 is installed by default on all derivatives of the default operating system.

**Comment by ValorNaram** [comment]
> Maybe the easiest way to fix this would be to put the language selection into a single icon

Please take a look on the image at [images/www.svg](https://github.com/babykarte/babykarte.github.io/blob/devel/images/www.svg)

I would suggest using this icon in order to save a bit of mobile data.
