### ISSUE TITLE
Diaper key support faulty

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte.github.io#97]
The diaper key is not evaluated correctly anymore. The information is not shown in the baby friendliness tab.

![grafik](https://user-images.githubusercontent.com/30999326/60389383-8fe41a80-9ac0-11e9-8c54-deffeb0bb3bf.png)

This problem does also exist in version 2.1. So the bug fix should also be committed to the master branch.

**Comment by Discostu36** [comment]
Still buggy in master branch

https://babykarte.github.io/#18&54.412405912306866&10.417039990425112

**Comment by ValorNaram** [comment]
Forgot to add parameters needed for comparation of the two keys. I really don't know why I committed without these parameters.

**Comment by Discostu36** [comment]
Still problems
https://babykarte.github.io/#18&54.41413977903825&10.415307283401491
![Screenshot_20190712-194430_Firefox](https://user-images.githubusercontent.com/30999326/61147876-cd43a180-a4dd-11e9-8771-bbd46b1e5971.jpg)

**Comment by ValorNaram** [comment]
First time I wrote an algorithm that sorts out two different types meaning the same thing.

Hopefully it works now finally.
